### ISSUE TITLE
CKEditor - throws error when clicking an ajax=false button after the editor was updated 

### ISSUE THREAD

**Issue by jxmai** [primefaces-extensions/primefaces-extensions.github.com#412]
# IMPORTANT
- If you open a issue, fill every item. Otherwise the issue might be closed as invalid.
- Before you open a issue, test it with the current/newest version.
## 1) Environment
- PrimeFaces version: Primefaces 6.0.5
- Does it work on the newest PrimeFaces version? No
- Application server + version: Tomcat v8.0
- Affected browsers: Chrome v53.0.2785.143 (64-bit)
## 2) Expected behavior

No error should be shown
## 3) Actual behavior

An error was thrown
## 4) Steps to reproduce

**Pre: Make sure to open a browser console to observe the error**

Step 1: Click the **updateContent** button on the top left 

Step 2: Click the **download** button at the bottom. (Please take a look at the console carefully, an error will be shown in this step)
---

During my debugging,

The error is :

![snapshot2](https://cloud.githubusercontent.com/assets/10467831/19316115/d80c2b9e-9065-11e6-97a6-62636615fe1b.png)

Step 1: Click the updateContent. insertAfter will be called the first time

![snapshot2](https://cloud.githubusercontent.com/assets/10467831/19316219/3b76fed4-9066-11e6-93cc-19d513ba83e4.png)

In Step 2: Click the download button.  The insertAfter function will be called the second time. The `a.$.nextSibling` is null

![snapshot2](https://cloud.githubusercontent.com/assets/10467831/19316309/96467858-9066-11e6-944c-492e77a02672.png)
## 5) Sample XHTML

``` html
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:p="http://primefaces.org/ui"
    xmlns:pe="http://primefaces.org/ui/extensions"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:fn="http://java.sun.com/jsp/jstl/functions"
    xmlns:c="http://java.sun.com/jsp/jstl/core">

    <h:head>

    </h:head>

    <h:body>
        <h:form>
            <p:commandButton process="@this" update="editor" value="updateContent"></p:commandButton>
            <pe:ckEditor id="editor"></pe:ckEditor>

            <p:commandButton ajax="false" value="download">
                <!-- <p:fileDownload value=""></p:fileDownload> -->
            </p:commandButton>
        </h:form>

    </h:body>

</ui:composition>
```

![snapshot2](https://cloud.githubusercontent.com/assets/10467831/19316406/e8a10f46-9066-11e6-87bf-d2a833e7dfeb.png)
## 6) Sample bean

N/A

**Comment by melloware** [comment]
I will try this out and let you know if I can reproduce. For PFE 6.1 we have upgraded the CKEditor version so it is possible this is fixed already.

**Comment by jxmai** [comment]
Thanks, I tried Primefaces Extension 6.1 snapshot (The most bleeding edge version). The issue is still there.

**Comment by jxmai** [comment]
@melloware The error will flash and disappear immediately due to page loading. As a hint, you can tried the following updated version. I completed the file download button so that the page won't be reloaded.

test.xhtml
```html
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:pe="http://primefaces.org/ui/extensions"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:fn="http://java.sun.com/jsp/jstl/functions"
	xmlns:c="http://java.sun.com/jsp/jstl/core">
	
	<h:head>
	
	</h:head>
	
	<h:body>
		<h:form enctype="multipart/form-data">
			<p:commandButton process="@this" update="editor" value="updateContent" actionListener="#{test.viewData()}"></p:commandButton>
			
			<pe:ckEditor id="editor">
			
			</pe:ckEditor>
			
			<p:commandButton ajax="false" value="download">
				<p:fileDownload value="#{test.file}"></p:fileDownload>
			</p:commandButton>
		</h:form>
		
	</h:body>

</ui:composition>

```

Test.java

```java
package ca.oltis.dmb.mbrapp.beans;

import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.io.Serializable;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;

import org.primefaces.model.DefaultStreamedContent;
import org.primefaces.model.StreamedContent;

@ViewScoped
@ManagedBean(name = "test")
public class Test implements Serializable {

    private static final long serialVersionUID = 8465294452198566201L;

    private String data;

    private transient StreamedContent file;

    public void viewData() {
        data = "<h1>Title <h1><table><tr><th>Col A</th><th>Col B</th><th>Col C</th><th>Col D</th><th>Col E</th></tr><tr><td>1</td><td>2</td><td>3</td><td>4</td><td>5</td></tr></table>";
    }

    public StreamedContent getFile() {
        InputStream in = new ByteArrayInputStream(getData().getBytes());
        this.file = new DefaultStreamedContent(in, "text/html", "result.html");
        return file;
    }

    public String getData() {
        return data;
    }

    public void setData(String data) {
        this.data = data;
    }

}

```

**Please follow the same step: Click updateContent, then click download**

![snapshot2](https://cloud.githubusercontent.com/assets/10467831/19325374/72baa754-908b-11e6-8647-2c97e599dfc5.png)

**Comment by melloware** [comment]
Great debugging!  If you want to take it the next step maybe see if you can come up with a solution?  Most bug fixes here are PR's at this point minus components devs own.

**Comment by jxmai** [comment]
will try :)  but I might need some help. The cause is still unknown to me

**Comment by jxmai** [comment]
After further debugging, the **form** might be one of the factors for this issue. I have created two download buttons:  one within form, and the other one outside the form.

```xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:pe="http://primefaces.org/ui/extensions"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:fn="http://java.sun.com/jsp/jstl/functions"
	xmlns:c="http://java.sun.com/jsp/jstl/core">
	
	<h:head>
	
	</h:head>
	
	<h:body>
		<h:form enctype="multipart/form-data">
			<p:commandButton process="@this" update="editor" value="updateContent" actionListener="#{test.viewData()}"></p:commandButton>
			<!-- <p:editor id="editor" value="#{test.data}"></p:editor> -->
			<!-- <p:textEditor id="editor" value="#{test.data}"></p:textEditor> -->
			
			<pe:ckEditor id="editor" value="#{test.data}"/>
			
			<p:commandButton ajax="false" value="download button in the same form">
				<p:fileDownload value="#{test.file}"></p:fileDownload>
			</p:commandButton>
			
		</h:form>
		
		<h:form>
			<p:commandButton ajax="false" value="download button in another form">
				<p:fileDownload value="#{test.file}"></p:fileDownload>
			</p:commandButton>
		</h:form>
		
	</h:body>

</ui:composition>
```

The ```insertAfter function``` will never get called when clicking the download button in another form

*Result: download worked OK, no error was thrown.*

---

After performing an ajax update to the editor, the ```insertAfter function``` will get called once when clicking the download button within the form  

*Result: an error was thrown. If you click the updateContent button again, a duplicate editor will be added.*

**Comment by melloware** [comment]
OK I was going to suggest trying that. I wonder if also enctype="multipart/form-data" is affecting it your second form doesn't have enctype="multipart/form-data".   But my real thought is that since the Download inside the same form as the CKEditor is doing a form submit on the whole form its contained in something about that is causing the issue.

**Comment by melloware** [comment]
Closing this one as Wont Fix since you have a better solution to move the Download button outside of the text editor form.

**Comment by jxmai** [comment]
The workaround is OK for my purposes, although it is a bug from personally speaking :) 

can keep it close until someone comes up with a better solution
