### ISSUE TITLE
Layout: Missing Center-pane Element Error

### ISSUE THREAD

**Issue by chopin111** [primefaces-extensions/primefaces-extensions.github.com#531]
Same issue as described [here](https://github.com/primefaces/primefaces/issues/3457) happens when using primefaces extensions components: `pe:layout` and `pe:layoutPane`.

**Comment by melloware** [comment]
Fixed with commit: https://github.com/primefaces-extensions/core/commit/213bf5cf27520e68f135c37de0038fdb2086c821

Will be part of 6.2.1 Patch release in the next couple of weeks!

**Comment by chopin111** [comment]
@melloware Sorry to bother, but we built extensions from sources with your fix, and the problem still exists. You can check this by running your [example](https://github.com/primefaces/primefaces/issues/3457#issuecomment-372134081) from PrimeFaces issue and replace `p:` layouts with their `pe:` equivalents. I also built PrimeFaces-core from current sources to check if this changes something but it didn't helped either :(

**Comment by melloware** [comment]
Confirmed.  I see the issue looking into fixing it.

**Comment by melloware** [comment]
OK I just checked in fixes.  Also the key to making this work is adding this to your web.xml.

```xml
    <context-param>
        <param-name>primefaces.MOVE_SCRIPTS_TO_BOTTOM</param-name>
        <param-value>true</param-value>
    </context-param>
```
This is a huge page performance optimization that moves all Javascript to the bottom of the page and executes it after the DOM is done loading.  It makes your pages speed up load time greatly and it solves this issue.

[pfe-531.zip](https://github.com/primefaces-extensions/primefaces-extensions.github.com/files/1811008/pfe-531.zip)

**Comment by chopin111** [comment]
Yay, now it works. Thank you!

**Comment by melloware** [comment]
Nice!  Thanks for reporting and helping me fix it!

**Comment by mallorygiles** [comment]
@melloware Is having the MOVE_SCRIPTS_TO_BOTTOM true a requirement to having the pe:layout function properly? This is not an option for me as it causes issues elsewhere. I have been able to use the p:layout with the fix that was in the primefaces 6.2.1 release without using that param, but the latest build of primefaces-extensions still has the issue unless, as you mentioned, the param value is set. I don't want to go to the primefaces layout since it's being depreciated and because of subtle differences in how the layout border is displayed that our users have become accustomed to.

**Comment by melloware** [comment]
@tandraschko I am kind of stumped on this one.  I made the same fix in PFE that I did in PF to move the "encodeScript" method into the "encodeEnd" section and it PF this fixed the issue where the script renders AFTER the dom but in PFE it still does not.  Any guidance on this?  I need the following..

```xml
<script id="layout_s" type="text/javascript">PrimeFaces.cw("ExtLayout","widget_layout");</script>
<div id="j_idt5" class="ui-layout-center ui-widget-content ui-corner-all pe-layout-pane-content"/>
```

To be...

```xml
<div id="j_idt5" class="ui-layout-center ui-widget-content ui-corner-all pe-layout-pane-content"/>
<script id="layout_s" type="text/javascript">PrimeFaces.cw("ExtLayout","widget_layout");</script>
```

**Comment by melloware** [comment]
as a note if I change to WidgetBuilder initWithWindowLoad() that also fixes it but to me I feel like I am missing something on why the script is getting rendered first?

**Comment by melloware** [comment]
Actually initWithWindowLoad fixes this scenario but then breaks another.

**Comment by tandraschko** [comment]
MOVE_SCRIPTS_TO_BOTTOM should actually add a $(function() {...}) arroudn the init script.

But the order how the script is rendered and the content depends on the renderer.
There is no magic in the WidgetBuilder.
AFAIR Oleg also used a temp ResponseWriter, maybe there is something wrong...

**Comment by tandraschko** [comment]
A rendere should do the following actually (not sure why oleg this somthing with a temp REsponseWriter and else):
1) render the component markup
2) render the child components
3) render the component script

**Comment by melloware** [comment]
OK I am looking at that as one of the only differences between the PF and PFE layout is that Temp ResponseWriter. Looks like he used that because in PFE you can pass your own "options" object to get serialized.  It has to be something with that.

**Comment by melloware** [comment]
@mallorygiles I just checked in some code can you do a rebuild of the SNAPSHOT and try your code again?   @tandraschko was right it was the temp ResponseWriter which I ended up entirely removing and all the code works and my test cases with no side effects.  So I am not sure why they were doing that before but it is definitely no longer needed as far as I can tell.

**Comment by mallorygiles** [comment]
Thanks. It works with the latest SNAPSHOT!

**Comment by melloware** [comment]
Excellent!  Nice teamwork everyone!

**Comment by tandraschko** [comment]
Could you check if the temp responseWriter is also used in other components? Maybe we have other bugs or just can remove it

**Comment by melloware** [comment]
6.2.1 Deployed in Maven Central!

**Comment by jxmai** [comment]
@melloware Could you please verify if the latest layout code is broken ? You may need to narrow the screen space a bit. Let's say pressing F12 on chrome to take up some space


Go to http://localhost:8080/primeext-showcase/sections/layout/fullPageLayout.jsf

![image](https://user-images.githubusercontent.com/10467831/37694713-5c0fe83a-2c97-11e8-85a9-f0c7806bb6c3.png)

```js
jquery.js.jsf?ln=primefaces&v=6.2:2 Uncaught RangeError: Maximum call stack size exceeded
    at String.replace (<anonymous>)
    at Function.camelCase (jquery.js.jsf?ln=primefaces&v=6.2:2)
    at Function.css (jquery.js.jsf?ln=primefaces&v=6.2:3)
    at Object.get (jquery.js.jsf?ln=primefaces&v=6.2:3)
    at Function.css (jquery.js.jsf?ln=primefaces&v=6.2:3)
    at jquery.js.jsf?ln=primefaces&v=6.2:4
    at T (jquery.js.jsf?ln=primefaces&v=6.2:3)
    at r.fn.init.r.fn.(anonymous function) [as outerHeight] (http://localhost:8080/primeext-showcase/javax.faces.resource/jquery/jquery.js.jsf?ln=primefaces&v=6.2:4:21576)
    at aa (layout.js.jsf?ln=primefaces-extensions&v=6.2:77)
    at String.<anonymous> (layout.js.jsf?ln=primefaces-extensions&v=6.2:131)
camelCase @ jquery.js.jsf?ln=primefaces&v=6.2:2
css @ jquery.js.jsf?ln=primefaces&v=6.2:3
get @ jquery.js.jsf?ln=primefaces&v=6.2:3
css @ jquery.js.jsf?ln=primefaces&v=6.2:3
(anonymous) @ jquery.js.jsf?ln=primefaces&v=6.2:4
T @ jquery.js.jsf?ln=primefaces&v=6.2:3
r.fn.(anonymous function) @ jquery.js.jsf?ln=primefaces&v=6.2:4
aa @ layout.js.jsf?ln=primefaces-extensions&v=6.2:77
(anonymous) @ layout.js.jsf?ln=primefaces-extensions&v=6.2:131
each @ jquery.js.jsf?ln=primefaces&v=6.2:2
ca @ layout.js.jsf?ln=primefaces-extensions&v=6.2:131
(anonymous) @ layout.js.jsf?ln=primefaces-extensions&v=6.2:132
each @ jquery.js.jsf?ln=primefaces&v=6.2:2
ca @ layout.js.jsf?ln=primefaces-extensions&v=6.2:131
(anonymous) @ layout.js.jsf?ln=primefaces-extensions&v=6.2:132
each @ jquery.js.jsf?ln=primefaces&v=6.2:2
ca @ layout.js.jsf?ln=primefaces-extensions&v=6.2:131
(anonymous) @ layout.js.jsf?ln=primefaces-extensions&v=6.2:132
each @ jquery.js.jsf?ln=primefaces&v=6.2:2
ca @ layout.js.jsf?ln=primefaces-extensions&v=6.2:131
(anonymous) @ layout.js.jsf?ln=primefaces-extensions&v=6.2:132
each @ jquery.js.jsf?ln=primefaces&v=6.2:2
ca @ layout.js.jsf?ln=primefaces-extensions&v=6.2:131
(anonymous) @ layout.js.jsf?ln=primefaces-extensions&v=6.2:132
each @ jquery.js.jsf?ln=primefaces&v=6.2:2
ca @ layout.js.jsf?ln=primefaces-extensions&v=6.2:131
(anonymous) @ layout.js.jsf?ln=primefaces-extensions&v=6.2:132
each @ jquery.js.jsf?ln=primefaces&v=6.2:2
ca @ layout.js.jsf?ln=primefaces-extensions&v=6.2:131
(anonymous) @ layout.js.jsf?ln=primefaces-extensions&v=6.2:132
each @ jquery.js.jsf?ln=primefaces&v=6.2:2
ca @ layout.js.jsf?ln=primefaces-extensions&v=6.2:131
(anonymous) @ layout.js.jsf?ln=primefaces-extensions&v=6.2:132
each @ jquery.js.jsf?ln=primefaces&v=6.2:2
ca @ layout.js.jsf?ln=primefaces-extensions&v=6.2:131
(anonymous) @ layout.js.jsf?ln=primefaces-extensions&v=6.2:132
each @ jquery.js.jsf?ln=primefaces&v=6.2:2
ca @ layout.js.jsf?ln=primefaces-extensions&v=6.2:131
(anonymous) @ layout.js.jsf?ln=primefaces-extensions&v=6.2:132
each @ jquery.js.jsf?ln=primefaces&v=6.2:2
ca @ layout.js.jsf?ln=primefaces-extensions&v=6.2:131
(anonymous) @ layout.js.jsf?ln=primefaces-extensions&v=6.2:132
each @ jquery.js.jsf?ln=primefaces&v=6.2:2
ca @ layout.js.jsf?ln=primefaces-extensions&v=6.2:131
(anonymous) @ layout.js.jsf?ln=primefaces-extensions&v=6.2:132
each @ jquery.js.jsf?ln=primefaces&v=6.2:2
ca @ layout.js.jsf?ln=primefaces-extensions&v=6.2:131
(anonymous) @ layout.js.jsf?ln=primefaces-extensions&v=6.2:132
each @ jquery.js.jsf?ln=primefaces&v=6.2:2
ca @ layout.js.jsf?ln=primefaces-extensions&v=6.2:131
(anonymous) @ layout.js.jsf?ln=primefaces-extensions&v=6.2:132
each @ jquery.js.jsf?ln=primefaces&v=6.2:2
ca @ layout.js.jsf?ln=primefaces-extensions&v=6.2:131
(anonymous) @ layout.js.jsf?ln=primefaces-extensions&v=6.2:132
each @ jquery.js.jsf?ln=primefaces&v=6.2:2
ca @ layout.js.jsf?ln=primefaces-extensions&v=6.2:131
(anonymous) @ layout.js.jsf?ln=primefaces-extensions&v=6.2:132
each @ jquery.js.jsf?ln=primefaces&v=6.2:2
ca @ layout.js.jsf?ln=primefaces-extensions&v=6.2:131
(anonymous) @ layout.js.jsf?ln=primefaces-extensions&v=6.2:132
each @ jquery.js.jsf?ln=primefaces&v=6.2:2
ca @ layout.js.jsf?ln=primefaces-extensions&v=6.2:131
(anonymous) @ layout.js.jsf?ln=primefaces-extensions&v=6.2:132
each @ jquery.js.jsf?ln=primefaces&v=6.2:2
ca @ layout.js.jsf?ln=primefaces-extensions&v=6.2:131
(anonymous) @ layout.js.jsf?ln=primefaces-extensions&v=6.2:132
each @ jquery.js.jsf?ln=primefaces&v=6.2:2
ca @ layout.js.jsf?ln=primefaces-extensions&v=6.2:131
(anonymous) @ layout.js.jsf?ln=primefaces-extensions&v=6.2:132
each @ jquery.js.jsf?ln=primefaces&v=6.2:2
ca @ layout.js.jsf?ln=primefaces-extensions&v=6.2:131
(anonymous) @ layout.js.jsf?ln=primefaces-extensions&v=6.2:132
each @ jquery.js.jsf?ln=primefaces&v=6.2:2
ca @ layout.js.jsf?ln=primefaces-extensions&v=6.2:131
(anonymous) @ layout.js.jsf?ln=primefaces-extensions&v=6.2:132
each @ jquery.js.jsf?ln=primefaces&v=6.2:2
ca @ layout.js.jsf?ln=primefaces-extensions&v=6.2:131
(anonymous) @ layout.js.jsf?ln=primefaces-extensions&v=6.2:132
each @ jquery.js.jsf?ln=primefaces&v=6.2:2
ca @ layout.js.jsf?ln=primefaces-extensions&v=6.2:131
(anonymous) @ layout.js.jsf?ln=primefaces-extensions&v=6.2:132
each @ jquery.js.jsf?ln=primefaces&v=6.2:2
ca @ layout.js.jsf?ln=primefaces-extensions&v=6.2:131
(anonymous) @ layout.js.jsf?ln=primefaces-extensions&v=6.2:132
each @ jquery.js.jsf?ln=primefaces&v=6.2:2
ca @ layout.js.jsf?ln=primefaces-extensions&v=6.2:131
(anonymous) @ layout.js.jsf?ln=primefaces-extensions&v=6.2:132
each @ jquery.js.jsf?ln=primefaces&v=6.2:2
ca @ layout.js.jsf?ln=primefaces-extensions&v=6.2:131
(anonymous) @ layout.js.jsf?ln=primefaces-extensions&v=6.2:132
each @ jquery.js.jsf?ln=primefaces&v=6.2:2
ca @ layout.js.jsf?ln=primefaces-extensions&v=6.2:131
(anonymous) @ layout.js.jsf?ln=primefaces-extensions&v=6.2:132
each @ jquery.js.jsf?ln=primefaces&v=6.2:2
ca @ layout.js.jsf?ln=primefaces-extensions&v=6.2:131
(anonymous) @ layout.js.jsf?ln=primefaces-extensions&v=6.2:132
each @ jquery.js.jsf?ln=primefaces&v=6.2:2
ca @ layout.js.jsf?ln=primefaces-extensions&v=6.2:131
(anonymous) @ layout.js.jsf?ln=primefaces-extensions&v=6.2:132
each @ jquery.js.jsf?ln=primefaces&v=6.2:2
ca @ layout.js.jsf?ln=primefaces-extensions&v=6.2:131
(anonymous) @ layout.js.jsf?ln=primefaces-extensions&v=6.2:132
each @ jquery.js.jsf?ln=primefaces&v=6.2:2
ca @ layout.js.jsf?ln=primefaces-extensions&v=6.2:131
(anonymous) @ layout.js.jsf?ln=primefaces-extensions&v=6.2:132
each @ jquery.js.jsf?ln=primefaces&v=6.2:2
ca @ layout.js.jsf?ln=primefaces-extensions&v=6.2:131
(anonymous) @ layout.js.jsf?ln=primefaces-extensions&v=6.2:132
each @ jquery.js.jsf?ln=primefaces&v=6.2:2
ca @ layout.js.jsf?ln=primefaces-extensions&v=6.2:131
(anonymous) @ layout.js.jsf?ln=primefaces-extensions&v=6.2:132
each @ jquery.js.jsf?ln=primefaces&v=6.2:2
ca @ layout.js.jsf?ln=primefaces-extensions&v=6.2:131
(anonymous) @ layout.js.jsf?ln=primefaces-extensions&v=6.2:132
each @ jquery.js.jsf?ln=primefaces&v=6.2:2
ca @ layout.js.jsf?ln=primefaces-extensions&v=6.2:131
(anonymous) @ layout.js.jsf?ln=primefaces-extensions&v=6.2:132
each @ jquery.js.jsf?ln=primefaces&v=6.2:2
ca @ layout.js.jsf?ln=primefaces-extensions&v=6.2:131
(anonymous) @ layout.js.jsf?ln=primefaces-extensions&v=6.2:132
each @ jquery.js.jsf?ln=primefaces&v=6.2:2
ca @ layout.js.jsf?ln=primefaces-extensions&v=6.2:131
(anonymous) @ layout.js.jsf?ln=primefaces-extensions&v=6.2:132
each @ jquery.js.jsf?ln=primefaces&v=6.2:2
ca @ layout.js.jsf?ln=primefaces-extensions&v=6.2:131
(anonymous) @ layout.js.jsf?ln=primefaces-extensions&v=6.2:132
each @ jquery.js.jsf?ln=primefaces&v=6.2:2
ca @ layout.js.jsf?ln=primefaces-extensions&v=6.2:131
(anonymous) @ layout.js.jsf?ln=primefaces-extensions&v=6.2:132
each @ jquery.js.jsf?ln=primefaces&v=6.2:2
ca @ layout.js.jsf?ln=primefaces-extensions&v=6.2:131
(anonymous) @ layout.js.jsf?ln=primefaces-extensions&v=6.2:132
each @ jquery.js.jsf?ln=primefaces&v=6.2:2
ca @ layout.js.jsf?ln=primefaces-extensions&v=6.2:131
(anonymous) @ layout.js.jsf?ln=primefaces-extensions&v=6.2:132
each @ jquery.js.jsf?ln=primefaces&v=6.2:2
ca @ layout.js.jsf?ln=primefaces-extensions&v=6.2:131
(anonymous) @ layout.js.jsf?ln=primefaces-extensions&v=6.2:132
each @ jquery.js.jsf?ln=primefaces&v=6.2:2
ca @ layout.js.jsf?ln=primefaces-extensions&v=6.2:131
(anonymous) @ layout.js.jsf?ln=primefaces-extensions&v=6.2:132
each @ jquery.js.jsf?ln=primefaces&v=6.2:2
ca @ layout.js.jsf?ln=primefaces-extensions&v=6.2:131
(anonymous) @ layout.js.jsf?ln=primefaces-extensions&v=6.2:132
each @ jquery.js.jsf?ln=primefaces&v=6.2:2
ca @ layout.js.jsf?ln=primefaces-extensions&v=6.2:131
(anonymous) @ layout.js.jsf?ln=primefaces-extensions&v=6.2:132
each @ jquery.js.jsf?ln=primefaces&v=6.2:2
ca @ layout.js.jsf?ln=primefaces-extensions&v=6.2:131
(anonymous) @ layout.js.jsf?ln=primefaces-extensions&v=6.2:132
each @ jquery.js.jsf?ln=primefaces&v=6.2:2
ca @ layout.js.jsf?ln=primefaces-extensions&v=6.2:131
(anonymous) @ layout.js.jsf?ln=primefaces-extensions&v=6.2:132
each @ jquery.js.jsf?ln=primefaces&v=6.2:2
ca @ layout.js.jsf?ln=primefaces-extensions&v=6.2:131
(anonymous) @ layout.js.jsf?ln=primefaces-extensions&v=6.2:132
each @ jquery.js.jsf?ln=primefaces&v=6.2:2
ca @ layout.js.jsf?ln=primefaces-extensions&v=6.2:131
(anonymous) @ layout.js.jsf?ln=primefaces-extensions&v=6.2:132
each @ jquery.js.jsf?ln=primefaces&v=6.2:2
ca @ layout.js.jsf?ln=primefaces-extensions&v=6.2:131
(anonymous) @ layout.js.jsf?ln=primefaces-extensions&v=6.2:132
each @ jquery.js.jsf?ln=primefaces&v=6.2:2
ca @ layout.js.jsf?ln=primefaces-extensions&v=6.2:131
(anonymous) @ layout.js.jsf?ln=primefaces-extensions&v=6.2:132
each @ jquery.js.jsf?ln=primefaces&v=6.2:2
ca @ layout.js.jsf?ln=primefaces-extensions&v=6.2:131
(anonymous) @ layout.js.jsf?ln=primefaces-extensions&v=6.2:132
each @ jquery.js.jsf?ln=primefaces&v=6.2:2
ca @ layout.js.jsf?ln=primefaces-extensions&v=6.2:131
(anonymous) @ layout.js.jsf?ln=primefaces-extensions&v=6.2:132
each @ jquery.js.jsf?ln=primefaces&v=6.2:2
ca @ layout.js.jsf?ln=primefaces-extensions&v=6.2:131
(anonymous) @ layout.js.jsf?ln=primefaces-extensions&v=6.2:132
each @ jquery.js.jsf?ln=primefaces&v=6.2:2
ca @ layout.js.jsf?ln=primefaces-extensions&v=6.2:131
(anonymous) @ layout.js.jsf?ln=primefaces-extensions&v=6.2:132
each @ jquery.js.jsf?ln=primefaces&v=6.2:2
ca @ layout.js.jsf?ln=primefaces-extensions&v=6.2:131
(anonymous) @ layout.js.jsf?ln=primefaces-extensions&v=6.2:132
each @ jquery.js.jsf?ln=primefaces&v=6.2:2
ca @ layout.js.jsf?ln=primefaces-extensions&v=6.2:131
(anonymous) @ layout.js.jsf?ln=primefaces-extensions&v=6.2:132
each @ jquery.js.jsf?ln=primefaces&v=6.2:2
ca @ layout.js.jsf?ln=primefaces-extensions&v=6.2:131
(anonymous) @ layout.js.jsf?ln=primefaces-extensions&v=6.2:132
each @ jquery.js.jsf?ln=primefaces&v=6.2:2
ca @ layout.js.jsf?ln=primefaces-extensions&v=6.2:131
(anonymous) @ layout.js.jsf?ln=primefaces-extensions&v=6.2:132
each @ jquery.js.jsf?ln=primefaces&v=6.2:2
ca @ layout.js.jsf?ln=primefaces-extensions&v=6.2:131
(anonymous) @ layout.js.jsf?ln=primefaces-extensions&v=6.2:132
each @ jquery.js.jsf?ln=primefaces&v=6.2:2
ca @ layout.js.jsf?ln=primefaces-extensions&v=6.2:131
(anonymous) @ layout.js.jsf?ln=primefaces-extensions&v=6.2:132
each @ jquery.js.jsf?ln=primefaces&v=6.2:2
ca @ layout.js.jsf?ln=primefaces-extensions&v=6.2:131
(anonymous) @ layout.js.jsf?ln=primefaces-extensions&v=6.2:132
each @ jquery.js.jsf?ln=primefaces&v=6.2:2
ca @ layout.js.jsf?ln=primefaces-extensions&v=6.2:131
```

**Comment by melloware** [comment]
hmmm i have tried everything and i can't make this happen.  Super small screen.  Opening F12, etc  This is definitely a call stack exceeded though while calculating some height.  Let me know if you have an exact way to duplicate it?

**Comment by jxmai** [comment]
Strangely I cannot replicate now. I will keep an eye on it however.

**Comment by JeeDevUser** [comment]
Hm.
The problem are still here, with primefaces-extensions-7.0.2.jar
Tried with 8.0RC1, but this time I got 
```
java.lang.AbstractMethodError: org.primefaces.extensions.component.layout.Layout.resolveWidgetVar()Ljava/lang/String;
	at org.primefaces.extensions.component.layout.LayoutRenderer.encodeScript(LayoutRenderer.java:94)
	at org.primefaces.extensions.component.layout.LayoutRenderer.encodeEnd(LayoutRenderer.java:85)

	at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:595)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1654)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1650)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1650)
```
so I am unable to run app at all

**Comment by melloware** [comment]
@JeeDevUser Are you sure you don't have 2 PrimeFaces JAR's in your path?  I use the Layout component in 2 productions apps with no issue.  If you are still having issues can you create a reproducible test case for me?

All of the examples on our showcase appear to be working and our showcase uses the pe:layout itself.

**Comment by JeeDevUser** [comment]
@melloware, sorry, this was my mistake. I had layout options class, in that class I was setting child layoutPanes that ware not defined. Classical copy-paste problem :-( Sorry again

**Comment by melloware** [comment]
No problem!
