### ISSUE TITLE
Sheet: sheetcolumn numericLocale not actually supported 

### ISSUE THREAD

**Issue by francescociani** [primefaces-extensions/primefaces-extensions.github.com#620]
pe:sheetcolumn parameter numericLocale is not actually supported meaning that if we specify a locale different from en-EN (for example it-IT or fr-FR) the decimal and thousands symbols remain the same ('.' for decimal ',' for thousands).

We tried passing both String or java.util.Locale.

Hint: we gave a look to HandsonTable sources and it seems that languages.min.js is not include in pe:sheet component. We spent some time but we were unable to add the file and correctly configure.

**Comment by melloware** [comment]
Thanks for reporting.  I will investigate and fix it.  I will post here once its fixed for you to test.

**Comment by melloware** [comment]
OK fixed with commit: https://github.com/primefaces-extensions/core/commit/81fc862b92fc3229aa7882189adc6aa6e2ae5883

You can build from sources to test it.

**Comment by francescociani** [comment]
Hi melloware,

we downloaded and built latest version but modifying price column in this way:

numericLocale="it-IT"  
numericPattern="$0.0,00"  

it is not working and still shows amount in en-US format.

Maybe the functionality is supported only in Handsontable 6.0.1; testing lastest version in jsfiddle works fine.

**Comment by melloware** [comment]
OK let me do some testing.

**Comment by melloware** [comment]
Can you send me your JS Fiddle? I am looking at their source code and they provide no Italian language pack.

These are the only langauages included:  https://github.com/handsontable/handsontable/tree/master/languages

**Comment by melloware** [comment]
In fact it looks like Italian is still in BETA: https://github.com/handsontable/handsontable/issues/5407

**Comment by francescociani** [comment]
Hi, actually we are not interested in Italian translation (our UserInterface is in english) but we need to use correct decimal and thousand separator based on user locale.

Not clear if translation and numeric symbols are related...

Thank you so much for your support.

Francesco

**Comment by melloware** [comment]
It looks like its locale dependent.  https://docs.handsontable.com/6.0.1/demo-numeric.html

So you need to set it to a Locale that has the format you are expecting.  Can you try 'de-DE' if you want EURO format?

**Comment by francescociani** [comment]
HI, we tried both de-DE and fr-FR but it is not working.

**Comment by melloware** [comment]
OK now I fixed it for REAL this time: https://github.com/primefaces-extensions/core/commit/b388c419d4b2265a623553fc8b07a944e9c4eae1

I upgrade to HandsonTable 6.0.1 and added the Numbro language pack which was missing.
